---
title: "STAT 651 Data Viz"
author: "Min Tamang"
date: "Nov 18, 2019"
output:
  html_document:
    df_print: paged
  pdf_document: default
---


## Choropleth maps

**Choropleth** maps add color to states or countries relative to a variable.
```{r}
library(pacman)
p_load(tidyverse, choroplethr, choroplethrMaps,RColorBrewer)
```

**State Population**
```{r}
data(df_pop_state)
pop_state <- df_pop_state %>% arrange(-(value))
top_n(pop_state,10)
```

```{r}
state_choropleth(df_pop_state, 
                 title  = "US 2012 State Population Estimates", 
                 legend = "Population")
```





**County Population**
```{r}
data(df_pop_county)
```


```{r}
county_choropleth(df_pop_county,
                 title  = "US 2012 County Population Estimates", 
                 legend = "Population", num_colors = 8)
```


**California Counties**
```{r}
county_choropleth(df_pop_county, 
                  title = "California County Population Estimates", 
                  legend = "Population",
                  state_zoom = "california")
```


**State Demographics**
```{r}
data("df_state_demographics")
head(df_state_demographics,10)
```


```{r}
# African American Population Distribution
df_state_demographics$value<- df_state_demographics$percent_black
state_choropleth(df_state_demographics, 
                 title  = "African American Population Distribution in US", 
                 legend = "Population")
```



```{r}
# White Population Distribution
df_state_demographics$value<- df_state_demographics$percent_white
state_choropleth(df_state_demographics, 
                 title  = "White Population Distribution in US", 
                 legend = "Population")
```



```{r}
# Asian Population Distribution
df_state_demographics$value<- df_state_demographics$percent_asian
state_choropleth(df_state_demographics, 
                 title  = "Asian Population Distribution in US", 
                 legend = "Population")
```


**World Map**
```{r}
data("df_pop_country")
country_pop <- df_pop_country %>% arrange(desc(value))
head(country_pop,10)

```
```{r}
country_choropleth(country_pop, 
                 title  = "World map based on population estimates", 
                 legend = "Population")
```

## Heatmap
**Heatmaps** visual the values in a matrix by adding color relative to a variable(s), usually down columns.
```{r}
data(df_state_demographics)
df_state_demographics <- df_state_demographics %>% arrange(total_population)

X <- data.matrix(df_state_demographics[,2:8])

row.names(X) <- df_state_demographics[,1]

head(X)
```

```{r}
heatmap(X, Rowv=NA, Colv=NA, col = brewer.pal(9, "Blues"), scale = "column")
```

